### ISSUE TITLE
Appcelerator is not recognizing the module?

### ISSUE THREAD

**Issue by mark22** [minhnc/tigmimagepicker#1]
I unzipped your ti.gmimagepicker-iphone-1.0.0.zip into my modules directory like I have for many other modules, but for some reason it doesn't show up at all in my modules list on the TiApp Editor

**Comment by minhnc** [comment]
You don't need to unzip module manually, just copy it to root of your project and run the app, the studio will do the rest. Check this out for more details - http://docs.appcelerator.com/platform/latest/#!/guide/Using_a_Module

**Comment by mark22** [comment]
Just not being recognized.  Do you know if there is a minimum SDK version requirement or anything?  Im on 5.3.1GA still ... 

Just FYI, I just counted.. I am using 18 other modules between iOS and Android with no problems btw

**Comment by minhnc** [comment]
sorry minsdk is 5.4.0.GA - https://github.com/minhnc/tigmimagepicker/blob/master/iphone/manifest

**Comment by minhnc** [comment]
I just downgraded minsdk to 5.1 - let me know if this work for you

https://github.com/minhnc/tigmimagepicker/blob/master/iphone/ti.gmimagepicker-iphone-1.0.0.zip

**Comment by mark22** [comment]
YES!  It recognizes the module now.  Thanks so much!  Going to start implementing it to make sure it works, but just want to report that it recognizes now.

Thanks much
